### ISSUE TITLE
preselected RF switch configuration (LMS6002D MyriadRF board)

### ISSUE THREAD

**Issue by tonjonGitHub** [myriadrf/LMS6002D-docs#9]
On page 12 of the MyriadRF Development Kit document (section 3.2, Rev 1.0r4, mod. 3/5/2013), there's a note for the test SMA connectors that says:
"Requires preselected RF switch configuration."

Not sure exactly what this means…

Wondering if this has anything to do with the GPIO table in section 3.7.

I suspect that I'm not getting the kind of output that I expect because I don't' have the "preselected RF switch configuration" set up right.

Does anybody know what this means?
Does anybody know how to set this from the "6002dr2.test" GUI?

Note that I'm using this with a Zipper board.

Thanks in advance..

**Comment by 9600** [comment]
The best place for this question would be the Reference Development Kit (Zipper) or LMS Driver (GUI) category of the discussion forum. 

  https://discourse.myriadrf.org/c/projects/reference-development-kit

  https://discourse.myriadrf.org/c/projects/lms-driver

If you could post your question there please. This issue tracker is really only for LMS7002D documentation errors.
